# Generated by Django 5.2.11 on 2026-02-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Video (MP4)'), ('audio', 'Audio (MP3)')], max_length=10)),
                ('name', models.CharField(help_text='Name to identify in admin', max_length=200)),
                ('file', models.FileField(blank=True, help_text='Upload MP4 or MP3 file.', null=True, upload_to='background_media/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Background media',
                'verbose_name_plural': 'Background media',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoxVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True, help_text='Legacy: used if per-type visibility is not used')),
                ('visible_no_light', models.BooleanField(default=True, help_text='Show on order page (No light type)')),
                ('visible_with_light', models.BooleanField(default=True, help_text='Show on order page (With light type)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Box variant',
                'verbose_name_plural': 'Box variants',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_mercadolibre', models.PositiveIntegerField(default=35000)),
                ('price_sin_luz', models.PositiveIntegerField(default=24000)),
                ('price_con_luz', models.PositiveIntegerField(default=42000)),
                ('price_pilas', models.PositiveIntegerField(default=2500)),
                ('transfer_alias', models.CharField(default='manu.perea13', max_length=100)),
                ('transfer_bank', models.CharField(default='Mercado Pago', max_length=100)),
                ('transfer_holder', models.CharField(default='Manuel Perea', max_length=200)),
                ('contact_whatsapp', models.CharField(default='+54 9 351 392 3790', max_length=50)),
                ('contact_email', models.CharField(default='copiiworld@gmail.com', max_length=254)),
                ('link_mercadolibre', models.URLField(blank=True, max_length=500)),
                ('video_sin_luz', models.CharField(blank=True, default='/static/videos/video-navidad.mp4', max_length=500)),
                ('video_con_luz', models.CharField(blank=True, default='/static/videos/background-video-2.mp4', max_length=500)),
                ('audio_sin_luz', models.CharField(blank=True, default='/static/audio/cancion-navidad.mp3', max_length=500)),
                ('audio_con_luz', models.CharField(blank=True, default='/static/audio/background-music-2.mp3', max_length=500)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='BoxVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.CharField(choices=[('no_light', 'No light'), ('with_light', 'With light')], max_length=20)),
                ('file', models.ImageField(blank=True, null=True, upload_to='variant_images/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='config.boxvariant')),
            ],
            options={
                'verbose_name': 'Box variant image',
                'verbose_name_plural': 'Box variant images',
                'ordering': ['variant', 'box_type', 'order'],
            },
        ),
    ]
