# Generated by Django 5.2.11 on 2026-02-24 20:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Cost settings (reference)',
                'verbose_name_plural': 'Cost settings (reference)',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('burbujas', 'Bubble roll'), ('caja_carton', 'Cardboard box (shipping)'), ('bolsa_ecommerce', 'Ecommerce bag'), ('publicidad_instagram', 'Instagram ads'), ('imagenes', 'Images'), ('pla_roll', 'PLA roll'), ('otro', 'Other')], max_length=40)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Units purchased (e.g. 10 boxes, or number of PLA rolls)')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('days', models.PositiveSmallIntegerField(blank=True, help_text='Period days (e.g. Instagram ads per week)', null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.CharField(blank=True, help_text='PLA only: color/variant (e.g. Graphite, Wood)', max_length=80)),
                ('brand', models.CharField(blank=True, help_text='PLA only: roll brand', max_length=120)),
                ('grams_per_roll', models.PositiveIntegerField(blank=True, help_text='PLA only: grams per roll (e.g. 1000). Cost per gram = (total_cost/quantity)/grams_per_roll', null=True)),
            ],
            options={
                'verbose_name': 'Purchase / expense',
                'verbose_name_plural': 'Purchases / expenses',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
