# Generated by Django 5.2.11 on 2026-02-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('burbujas', 'Bubble roll'), ('caja_carton', 'Cardboard box (shipping)'), ('bolsa_ecommerce', 'Ecommerce bag'), ('publicidad_instagram', 'Instagram ads'), ('imagenes', 'Images'), ('pla_roll', 'PLA rollo'), ('otro', 'Other')], max_length=40),
        ),
    ]
