# Generated by Django 5.2.11 on 2026-02-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('box_type', models.CharField(blank=True, choices=[('no_light', 'No light'), ('with_light', 'With light')], help_text='no_light | with_light', max_length=20)),
                ('led_type', models.CharField(blank=True, choices=[('warm_led', 'Warm LED'), ('white_led', 'White LED')], help_text='Only if box_type=with_light', max_length=20)),
                ('variant', models.CharField(blank=True, choices=[('graphite', 'Graphite'), ('wood', 'Wood'), ('black', 'Black'), ('marble', 'Marble'), ('graphite_light', 'Graphite (with light)'), ('wood_light', 'Wood (with light)'), ('black_light', 'Black (with light)'), ('marble_light', 'Marble (with light)')], help_text='graphite, wood, black, marble, *_light', max_length=50)),
                ('shipping_option', models.CharField(blank=True, choices=[('pickup_uber', 'Pickup / Uber'), ('shipping_province', 'Shipping to other province')], help_text='pickup_uber | shipping_province', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('processing', 'Finalized'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('deposit', models.BooleanField(default=False, help_text='Deposit (seña) received')),
                ('active', models.BooleanField(default=True, help_text='If False, order is hidden from admin table (not deleted)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/%d/')),
                ('cost_snapshot', models.JSONField(blank=True, help_text='Cost snapshot when finalizing: cost_caja, cost_pla, cost_empaque, total.', null=True)),
                ('price_snapshot', models.JSONField(blank=True, help_text='Sale price when finalized: precio_venta (no_light or with_light+batteries).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('caja_carton', 'Cardboard box (shipping)'), ('bolsa_ecommerce', 'Ecommerce bag')], max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Packaging stock',
                'verbose_name_plural': 'Packaging stock',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('graphite', 'graphite'), ('wood', 'wood'), ('black', 'black'), ('marble', 'marble')], max_length=50)),
                ('box_type', models.CharField(choices=[('no_light', 'No light'), ('with_light', 'With light')], default='no_light', help_text='no_light | with_light', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'unique_together': {('variant', 'box_type')},
            },
        ),
        migrations.CreateModel(
            name='ImageCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='Slot index (0-9)')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/%Y/%m/%d/')),
                ('crop_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_crops', to='orders.order')),
            ],
            options={
                'ordering': ['order', 'display_order', 'slot'],
                'unique_together': {('order', 'slot')},
            },
        ),
    ]
