# Generated by Django 5.2.11 on 2026-02-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_sent_to_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('processing', 'Finalized'), ('delivered', 'Delivered')], default='draft', max_length=20),
        ),
    ]
