# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sena',
            field=models.BooleanField(default=False, help_text='Seña (deposit) received'),
        ),
    ]
