# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_order_sena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sena',
            new_name='deposit',
        ),
    ]
