# Generated by Django 5.2.11 on 2026-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_sena_to_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden_from_dashboard',
            field=models.BooleanField(default=False, help_text='If True, order is hidden from admin table (not deleted)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.BooleanField(default=False, help_text='Deposit (seña) received'),
        ),
    ]
