# Generated by Django (manual)

from django.db import migrations, models


def invert_active(apps, schema_editor):
    """hidden_from_dashboard True (hidden) -> active False; False (visible) -> active True."""
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.active = not order.active
        order.save(update_fields=['active'])


def invert_active_reverse(apps, schema_editor):
    """Reverse: invert again so that after RenameField back, hidden_from_dashboard has original values."""
    invert_active(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_hidden_from_dashboard_alter_order_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hidden_from_dashboard',
            new_name='active',
        ),
        migrations.RunPython(invert_active, invert_active_reverse),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, help_text='If False, order is hidden from admin table (not deleted)'),
        ),
    ]
