# Generated by Django 5.2.11 on 2026-02-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_stock_by_box_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='orders_stock_variant_box_type_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('variant', 'box_type')},
        ),
    ]
